---
# See https://github.com/kubernetes/kubernetes/issues/33789
- name: up cbr0
  become: true
  command: /bin/sh -c "( ifdown cbr0 || true ) && ifup cbr0"

- name: docker reload
  become: true
  command: systemctl daemon-reload

- name: docker restart
  become: true
  command: systemctl restart docker

