---
kind: Pod
apiVersion: v1
metadata:
  name: etcd
  namespace: kube-system
  labels:
    component: etcd
    tier: control-plane
spec:
  hostNetwork: true
  containers:
  - name: etcd
    image: gcr.io/google_containers/etcd-amd64:2.2.5
    command:
    - etcd
    - --listen-client-urls=http://127.0.0.1:2379
    - --advertise-client-urls=http://127.0.0.1:2379
    - --data-dir=/var/etcd/data
    resources:
      requests:
        cpu: 200m
    volumeMounts:
    - name: etcd
      mountPath: "/var/etcd"
    livenessProbe:
      httpGet:
        path: "/health"
        port: 2379
        host: 127.0.0.1
      initialDelaySeconds: 15
      timeoutSeconds: 15
    securityContext:
      seLinuxOptions:
        type: unconfined_t
  volumes:
  - name: etcd
    hostPath:
      path: "/var/lib/etcd"

