---
kind: Pod
apiVersion: v1
metadata:
  name: kube-scheduler
  namespace: kube-system
  labels:
    component: kube-scheduler
    tier: control-plane
spec:
  hostNetwork: true
  containers:
  - name: kube-scheduler
    image: gcr.io/google_containers/kube-scheduler-amd64:{{ kubernetes_image_version }}
    command:
    - /usr/local/bin/kube-scheduler
    - --v=4
    - --address=127.0.0.1
    - --leader-elect
    - --kubeconfig=/etc/kubernetes/pki/scheduler/kubeconfig
    resources:
      requests:
        cpu: 100m
    livenessProbe:
      httpGet:
        path: /healthz
        port: 10251
        host: 127.0.0.1
      initialDelaySeconds: 15
      timeoutSeconds: 15
    volumeMounts:
    - name: pki
      readOnly: true
      mountPath: /etc/kubernetes/pki/scheduler
  volumes:
  - name: pki
    hostPath:
      path: /etc/kubernetes/pki/scheduler

